apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-playground-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/devops-playground

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-playground-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
