apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-app
  namespaceSelector:
    matchNames:
      - default   # namespace
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
