apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-playground-be
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: devops-playground-be
  namespaceSelector:
    matchNames:
      - default
      - dev
      - test
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
