apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-playground-be-test
  namespace: argocd
spec:
  project: default

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: devops-playground-be-test
      namespace: test
      jsonPointers:
        - /spec/replicas

  source:
    repoURL: https://github.com/max-nguyen-3006/devops-playground-deploy.git
    targetRevision: HEAD
    path: node/be/overlays/test

  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
