apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-playground-be-hpa
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
