apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-playground-be
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: devops-playground-be
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 2Gi
