apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-playground-be
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: devops-playground-be
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
